name: Obsidian Notifier

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Клонируем репозиторий
        uses: actions/checkout@v3

      - name: 🐍 Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Устанавливаем зависимости
        run: pip install -r requirements.txt

      - name: 🚀 Запускаем main.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TOPIC_ID: ${{ secrets.TOPIC_ID }}
          TASKS_FOLDER: tasks
        run: python main.py
